version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    target-branch: main

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    target-branch: main
